// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Endjin.Imm.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AgeBasedRule")]
    public partial class AgeBasedRuleFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AgeBasedRule.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AgeBasedRule", "\tIn order to detect when some aspect of IP is stale\r\n\tAs a developer looking at s" +
                    "ome IP\r\n\tI want age-related measures to be accurate even if the maturity matrix " +
                    "has not been updated in a long while", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Score",
                        "Age",
                        "Description"});
            table1.AddRow(new string[] {
                        "3",
                        "<P1M",
                        "< 1 month"});
            table1.AddRow(new string[] {
                        "2",
                        "<P3M",
                        "> 1 month"});
            table1.AddRow(new string[] {
                        "1",
                        "\'*\'",
                        "> 3 months"});
            table1.AddRow(new string[] {
                        "0",
                        "",
                        "None"});
#line 7
    testRunner.Given("I have a rule named \'Date of Last IP Review\' with id \'da4ed776-0365-4d8a-a297-c4e" +
                    "91a14d646\' and DataType \'Age\'", ((string)(null)), table1, "Given ");
#line 13
    testRunner.And("the reference date for evaluation purposes is \'2019-12-03\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Less than one month old")]
        [NUnit.Framework.TestCaseAttribute("2019-12-03", null)]
        [NUnit.Framework.TestCaseAttribute("2019-11-30", null)]
        [NUnit.Framework.TestCaseAttribute("2019-11-04", null)]
        public virtual void LessThanOneMonthOld(string date, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Less than one month old", null, exampleTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 16
    testRunner.Given(string.Format("my IMM has an entry named \'Date of Last IP Review\' with id \'da4ed776-0365-4d8a-a2" +
                        "97-c4e91a14d646\' with a Date of \'{0}\'", date), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
    testRunner.When("I evaluate the IMM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
    testRunner.Then("the score for the \'da4ed776-0365-4d8a-a297-c4e91a14d646\' rule should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Between one and three months old")]
        [NUnit.Framework.TestCaseAttribute("2019-11-03", null)]
        [NUnit.Framework.TestCaseAttribute("2019-11-02", null)]
        [NUnit.Framework.TestCaseAttribute("2019-10-15", null)]
        [NUnit.Framework.TestCaseAttribute("2019-09-04", null)]
        public virtual void BetweenOneAndThreeMonthsOld(string date, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Between one and three months old", null, exampleTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 32
    testRunner.Given(string.Format("my IMM has an entry named \'Date of Last IP Review\' with id \'da4ed776-0365-4d8a-a2" +
                        "97-c4e91a14d646\' with a Date of \'{0}\'", date), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
    testRunner.When("I evaluate the IMM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
    testRunner.Then("the score for the \'da4ed776-0365-4d8a-a297-c4e91a14d646\' rule should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("At least three months old")]
        [NUnit.Framework.TestCaseAttribute("2019-09-03", null)]
        [NUnit.Framework.TestCaseAttribute("2019-09-01", null)]
        [NUnit.Framework.TestCaseAttribute("2019-01-01", null)]
        [NUnit.Framework.TestCaseAttribute("2018-12-04", null)]
        [NUnit.Framework.TestCaseAttribute("2018-12-03", null)]
        public virtual void AtLeastThreeMonthsOld(string date, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("At least three months old", null, exampleTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 44
    testRunner.Given(string.Format("my IMM has an entry named \'Date of Last IP Review\' with id \'da4ed776-0365-4d8a-a2" +
                        "97-c4e91a14d646\' with a Date of \'{0}\'", date), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
    testRunner.When("I evaluate the IMM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
    testRunner.Then("the score for the \'da4ed776-0365-4d8a-a297-c4e91a14d646\' rule should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Date not specified")]
        public virtual void DateNotSpecified()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Date not specified", null, ((string[])(null)));
#line 56
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 57
    testRunner.Given("my IMM has an entry named \'Date of Last IP Review\' with id \'da4ed776-0365-4d8a-a2" +
                    "97-c4e91a14d646\' with no Date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
    testRunner.When("I evaluate the IMM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
    testRunner.Then("the score for the \'da4ed776-0365-4d8a-a297-c4e91a14d646\' rule should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Legacy format")]
        [NUnit.Framework.TestCaseAttribute("0", "None", null)]
        [NUnit.Framework.TestCaseAttribute("1", "> 3 months", null)]
        [NUnit.Framework.TestCaseAttribute("2", "> 1 month", null)]
        [NUnit.Framework.TestCaseAttribute("3", "< 1 month", null)]
        public virtual void LegacyFormat(string score, string description, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Legacy format", null, exampleTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
this.FeatureBackground();
#line 62
    testRunner.Given(string.Format("my IMM has an entry named \'Date of Last IP Review\' with id \'da4ed776-0365-4d8a-a2" +
                        "97-c4e91a14d646\' with a Score of {0} and description of \'{1}\'", score, description), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
    testRunner.When("I evaluate the IMM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
    testRunner.Then(string.Format("the score for the \'da4ed776-0365-4d8a-a297-c4e91a14d646\' rule should be {0}", score), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
